APP/urls.py
import glob
from os.path import join
from pathlib import Path

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import URLPattern, URLResolver
from django.urls import include, path
from django.views.static import serve

import projects.views

urlpatterns = [
    path('', projects.views.objects_table, name='index'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
]

for each in glob.glob(join(settings.BASE_DIR / '*', "urls.py")):
    if 'APP' in each:
        continue
    app = Path(each).resolve().parent.name
    urlpatterns += [path('', include(f'{app}.urls'))]


@login_required
def protected_serve(request, path, document_root=None, show_indexes=False):
    return serve(request, path, document_root, show_indexes)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, protected_serve, document_root=settings.MEDIA_ROOT)

handler404 = 'main.errors.my404'


def get_urls():
    result = []
    for each in list_urls(urlpatterns):
        url = ''.join(each)
        if 'accounts/' in url:
            continue
        if 'admin/' in url:
            continue
        if 'i18n/' in url:
            continue
        if 'media/' in url:
            continue
        result.append(f'/{url}'.replace('<int:id>', '1'))
    return result


def list_urls(lis, acc=None):
    if acc is None:
        acc = []
    if not lis:
        return
    l = lis[0]
    if isinstance(l, URLPattern):
        yield acc + [str(l.pattern)]
    elif isinstance(l, URLResolver):
        yield from list_urls(l.url_patterns, acc + [str(l.pattern)])
    yield from list_urls(lis[1:], acc)

BM/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import include, path
from django.views.static import serve


@login_required
def protected_serve(request, path, document_root=None, show_indexes=False):
    return serve(request, path, document_root, show_indexes)


urlpatterns = [
    path('', include('Baumanagement.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, protected_serve, document_root=settings.MEDIA_ROOT)

handler404 = 'Baumanagement.views.views.my404'

products/urls.py
from django.urls import path

import products.views
import products.views_labels

urlpatterns = [
    path("productcategories", products.views_labels.objects_table, name="productcategories"),
    path("productcategory/<int:id>", products.views_labels.object_table, name="productcategory_id"),

    path("products", products.views.objects_table, name="products"),
    path("product/<int:id>", products.views.object_table, name="product_id")
]

files/models.py
import os

from author.decorators import with_author
from django.db import models
from django.utils.translation import gettext_lazy as _

from main.models import BaseModel, FileModel


@with_author
class File(BaseModel):
    name = models.CharField(max_length=256, null=False, blank=False, verbose_name=_('Name'))
    file = models.FileField(blank=False, upload_to="%Y/%m/%d", verbose_name=_('Files'))

    class Meta:
        verbose_name = _('File')
        verbose_name_plural = _('Files')

    def delete(self, *args, **kwargs):
        os.remove(self.file.path) if os.path.exists(self.file.path) else None
        for cls in FileModel.__subclasses__():
            for obj in cls.objects.all():
                if self.id in obj.file_ids:
                    obj.file_ids.remove(self.id)
                    obj.save()
        super().delete(*args, **kwargs)

main/models.py
from decimal import Decimal

from colorfield.fields import ColorField
from django.core.validators import MinValueValidator
from django.db import models
from django.db.models import Q
from django.utils.translation import gettext_lazy as _


class BaseModel(models.Model):
    created = models.DateTimeField(auto_now_add=True, verbose_name=_('Created'))
    updated = models.DateTimeField(auto_now=True, verbose_name=_('Updated'))
    open = models.BooleanField(default=True, null=False, blank=False, verbose_name=_('Open'))
    comment_ids = models.JSONField(default=list, null=False, blank=True, verbose_name=_('Comments'))

    class Meta:
        abstract = True

    def __str__(self):
        return self.name

    @classmethod
    def verbose_name(cls):
        return cls._meta.verbose_name


class AddressModel(models.Model):
    address = models.CharField(max_length=256, null=False, blank=True, verbose_name=_('Address'))
    city = models.CharField(max_length=256, null=False, blank=True, verbose_name=_('City'))
    land = models.CharField(max_length=256, null=False, blank=True, verbose_name=_('Land'), default='Deutschland')

    class Meta:
        abstract = True


class PriceModel(models.Model):
    amount_netto_positiv = models.DecimalField(max_digits=10, decimal_places=2, null=False, blank=False,
                                               verbose_name=_('Amount netto'), default=0,
                                               validators=[MinValueValidator(Decimal('0.00'))])
    amount_brutto_positiv = models.DecimalField(max_digits=10, decimal_places=2, null=False, blank=False,
                                                verbose_name=_('Amount brutto'), default=0,
                                                validators=[MinValueValidator(Decimal('0.00'))])
    vat = models.FloatField(null=False, blank=False, verbose_name=_('VAT %'), default=19,
                            validators=[MinValueValidator(float(0))])

    BUY = 'buy'
    SELL = 'sell'
    TYPE_CHOISES = [
        (BUY, _('Buy')),
        (SELL, _('Sell')),
    ]

    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        if self.amount_netto_positiv and not self.amount_brutto_positiv:
            self.save_count_brutto(*args, **kwargs)
        elif not self.amount_netto_positiv and self.amount_brutto_positiv:
            self.save_count_netto(*args, **kwargs)
        elif self.amount_netto_positiv and not self.vat and self.amount_brutto_positiv:
            self.save_count_vat(*args, **kwargs)
        else:
            self.save_count_brutto(*args, **kwargs)  # ToDo form validation

    def save_count_netto(self, *args, **kwargs):
        self.amount_netto_positiv = Decimal(float(self.amount_brutto_positiv) * 100 / (100 + self.vat))
        super().save(*args, **kwargs)

    def save_count_brutto(self, *args, **kwargs):
        self.amount_brutto_positiv = Decimal(float(self.amount_netto_positiv) * (100 + self.vat) / 100)
        super().save(*args, **kwargs)

    def save_count_vat(self, *args, **kwargs):
        if self.amount_netto_positiv != 0:
            self.vat = round((self.amount_brutto_positiv / self.amount_netto_positiv - 1) * 100, 3)
        else:
            self.vat = 0.0
        super().save(*args, **kwargs)


class FileModel(models.Model):
    file_ids = models.JSONField(default=list, null=False, blank=True, verbose_name=_('Files'))

    class Meta:
        abstract = True

    @property
    def files(self):
        from files.models import File
        return list(filter(None, [get_or_none(File, id=id) for id in self.file_ids]))


class Label(models.Model):
    name = models.CharField(max_length=256, null=False, blank=False, verbose_name=_('Name'))
    parent = models.ForeignKey('self', on_delete=models.RESTRICT, null=True, blank=True,
                               verbose_name=_('Classify label under'), related_name='children')
    color = ColorField(default='#FFFFFF')
    path = models.TextField(max_length=256, null=True, blank=True, verbose_name=_('Full path'), unique=True)

    class Meta:
        abstract = True

    def __str__(self):
        return self.path

    @staticmethod
    def extra_fields(qs):
        return qs.order_by('path')

    @classmethod
    def check_parents(cls, obj):
        if obj.parent:
            return 1 + cls.check_parents(obj.parent)
        return 1

    def tree_view(self):
        deep = self.check_parents(self.parent) if self.parent else 0
        return '&emsp;' * deep + self.path

    @classmethod
    def root_labels(cls):
        return cls.objects.filter(parent__isnull=True).order_by('name')

    @classmethod
    def update_children(cls, children):
        for each in children:
            each.save(recursive=False)
            if each.children:
                cls.update_children(each.children.all())

    def save(self, *args, **kwargs):
        self.path = f'{self.parent}/{self.name}' if self.parent else self.name
        recursive = kwargs.pop('recursive', True)
        super().save(*args, **kwargs)
        if recursive:
            self.update_children(self.children.all())


def add_search_field(queryset, request):
    search = request.GET.get('search')
    if search is not None and queryset:
        qs = Q()
        for query in [Q(**{f'{field}__icontains': search}) for field in queryset[0].__class__.search_fields]:
            qs = qs | query
        queryset = queryset.filter(qs)
    return queryset


def get_base_models():
    result = {}
    for cls in BaseModel.__subclasses__():
        result[cls.__name__.lower()] = cls
    return result


def get_or_none(cls, **kwargs):
    try:
        return cls.objects.get(**kwargs)
    except cls.DoesNotExist:
        return None

main/forms.py
from django.forms import TextInput, forms


class EmptyForm(forms.Form):
    base_fields = 'base',


class ColorFieldWidget(TextInput):
    input_type = 'color'

main/views.py
import inspect

from django.db import IntegrityError
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django_tables2 import RequestConfig

from comments.models import Comment
from files.models import File
from main.comments import CommentFormClass, add_comment_to_object
from main.models import add_search_field, get_or_none
from main.table_filters import filter_objects_table
from main.upload_files import upload_files
from notifications.models import Notification


def generate_objects_table(request, context, baseClass, tableClass, formClass, queryset=None):
    settings = context['settings']
    if 'created' in baseClass.table_fields:
        context['date_fields'] = True

    if not request.GET:
        context.setdefault('breadcrumbs_titel', baseClass._meta.verbose_name_plural)
        context.setdefault('breadcrumbs', [{'text': _("All")}])
        new_object_form(request, context, formClass)
        context['search_field'] = True
    # else:
    if queryset is None:
        queryset = baseClass.objects

    queryset = filter_objects_table(request, baseClass, queryset, settings)

    if request.GET.get('sort'):
        settings.sort[baseClass.urls] = request.GET.get('sort')
        settings.save()

    queryset = baseClass.extra_fields(queryset)
    queryset = add_search_field(queryset, request)
    table1 = tableClass(queryset, order_by=settings.sort.get(baseClass.urls, '-created'), settings=settings)
    RequestConfig(request).configure(table1)
    context['table1'] = table1


def generate_object_table(request, context, baseClass, tableClass, formClass, queryset):
    settings = context['settings']
    if not request.GET:
        context.setdefault('breadcrumbs_titel', baseClass._meta.verbose_name)
        edit_object_form(request, context, formClass, queryset.first())

        comments = []
        for comment in [get_or_none(Comment, id=id) for id in queryset.first().comment_ids]:
            if comment:
                comments.append({
                    'object': comment,
                    'files': list(filter(None, [get_or_none(File, id=id) for id in comment.file_ids]))
                })
        context['tables'].append({'titel': _('Comments'), 'count': len(comments),
                                  'comments': comments, 'form': CommentFormClass(), 'files_form': []})
    # else:
    queryset = baseClass.extra_fields(queryset)
    table1 = tableClass(queryset, orderable=False, object_table=True, settings=settings)
    RequestConfig(request).configure(table1)
    context['table1'] = table1


def generate_next_objects_table(request, context, baseClass, tableClass, queryset, titel=None):
    settings = context['settings']
    queryset = baseClass.extra_fields(queryset)
    table = tableClass(queryset, order_by=settings.sort.get(baseClass.urls, '-created'), settings=settings,
                       orderable=2)  # hack. ordered, but without a links in header
    RequestConfig(request).configure(table)
    context['tables'].append({'table': table, 'titel': titel or baseClass._meta.verbose_name_plural,
                              'count': len(table.rows), 'link': f'{request.path}/{baseClass.urls}'})


def create_new_object_or_get_error(request, cls):
    if request.method != 'POST':
        return None
    formset = cls(request.POST, request.FILES)
    if formset.is_valid():
        try:
            new_object = formset.save(commit=False)
            new_object.save()
            formset.save_m2m()
            verbose_name = new_object.verbose_name()
            link = reverse(new_object.url_id, args=[new_object.id])
            Notification.message(
                request, f'{verbose_name} "<a href="{link}">{new_object.name}</a>" ' + _("created"), 'SUCCESS'
            )
            upload_files(request, new_object)
            add_comment_to_object(request, new_object)
            return None
        except IntegrityError:
            Notification.message(request, _("Object already exist"), 'ERROR')
    else:
        return formset


def new_object_form(request, context, cls):
    error_form = create_new_object_or_get_error(request, cls)
    context['form'] = error_form or context.get('form') or cls()
    if 'FileModel' in str(inspect.getmro(cls.Meta.model)):
        context['files_form'] = []
    context['buttons'] = ['New']


def edit_object_form(request, context, cls, object):
    error_form = None
    if request.method == 'POST':
        if request.POST.get('mainObject'):
            formset = cls(request.POST, request.FILES, instance=object)
            if formset.is_valid():
                object = formset.save(commit=False)
                object.save()
                formset.save_m2m()
                verbose_name = object.verbose_name()
                link = reverse(object.url_id, args=[object.id])
                Notification.message(
                    request, f'{verbose_name} "<a href="{link}">{object.name}</a>" ' + _("changed"), 'SUCCESS'
                )
                upload_files(request, object)
            error_form = formset
        elif request.POST.get('createCopy'):
            error_form = create_new_object_or_get_error(request, cls)
        elif request.POST.get('editProducts'):
            pass
    context['form'] = error_form or context.get('form') or cls(instance=object)
    if 'FileModel' in str(inspect.getmro(object.__class__)):
        context['files_form'] = object.files
    context['buttons'] = ['Edit']

products/views.py
from django import forms
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from main.view_functions import get_base_context
from main.view_renders import myrender
from main.views import generate_objects_table, generate_object_table
from products.models import Product
from products.models_labels import ProductCategory
from products.tables import ProductTable

baseClass = Product
tableClass = ProductTable
labelClass = ProductCategory


class FormClass(forms.ModelForm):
    class Meta:
        model = baseClass
        fields = baseClass.form_fields


@login_required
def objects_table(request):
    context = get_base_context(request)
    context['categories'] = {'objects': labelClass.objects.order_by('path'),
                             'urls': labelClass.urls}
    generate_objects_table(request, context, baseClass, tableClass, FormClass)
    return myrender(request, context)


@login_required
def object_table(request, id):
    context = get_base_context(request)
    queryset = baseClass.objects.filter(id=id)
    if queryset.first() is None:
        raise Http404

    context['breadcrumbs'] = [{'link': reverse(baseClass.urls), 'text': _("All")},
                              {'text': queryset.first()}]

    generate_object_table(request, context, baseClass, tableClass, FormClass, queryset)
    return myrender(request, context)

templates/tables/find_product_in_DB.html
{% load filters %}

<input type="hidden" name="products-{{ forloop.counter0 }}-product" id="id_products-{{ forloop.counter0 }}-product"
       value="{% if forloop.counter0 < products.count %}{% with products|list_index:forloop.counter0 as product %}{{ product.product.id }}{% endwith %}{% endif %}">
<input type="text" name="products-{{ forloop.counter0 }}-product_name" id="id_products-{{ forloop.counter0 }}-product_name"
       value="{% if forloop.counter0 < products.count %}{% with products|list_index:forloop.counter0 as product %}{{ product.product.name }}{% endwith %}{% endif %}">

templates/tables/labels.html
{% load i18n %}

{% if labels %}
<div class="row labels">
    <div class="col">
        <a href="" onclick="mainTableLabel('');return false;">{% trans 'All' %}</a>
        {% for label in labels.objects %}
        &emsp;#<a href="" onclick="mainTableLabel({{label.id}});return false;">{{label.path}}</a>
        {% endfor %}
        &emsp;&#9881;<a href="{% url labels.urls %}">{% trans 'Manage labels' %}</a>
    </div>
</div>
{% endif %}

{% if categories %}
<div class="row labels align-items-center">
    <div class="col-auto">
        <select class="form-select form-select-sm mt-2 mb-2" aria-label=".form-select-sm example"
                oninput="mainTableReload()" id="product_category">
            <option value="" selected>{% trans 'All products' %}</option>
            {% for category in categories.objects %}
            <option value="{{ category.id }}">{{ category.tree_view|safe }}</option>
            {% endfor %}
        </select>
    </div>
    <div class="col-auto">
        &#9881;<a href="{% url categories.urls %}">{% trans 'Manage categories' %}</a>
    </div>
</div>
<script>
        document.getElementById("product_category").addEventListener('focusin', setInputBackground);
        document.getElementById("product_category").addEventListener('focusout', setInputBackground);
</script>
{% endif %}

templates/tables/maintable.html
{% load render_table from django_tables2 %}

<div class="col">
    {% render_table table1 %}
</div>

templates/tables/messages.html
{% load i18n %}
{% load static %}

{% if messages %}
<div class="toast-container position-fixed bottom-0 end-0 p-3" style="z-index: 1031">
    {% for message in messages %}
    <div class="toast" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="toast-header">
            <img class="rounded me-2" src="{% static 'favicon-48x48.png' %}" alt="Baumanagement" width="24"
                 height="24"/>
            <strong class="me-auto">{% translate 'Notification' %}</strong>
            <small class="text-muted">{% translate 'just now' %}</small>
            <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="{% trans 'Close' %}"></button>
        </div>
        <div class="toast-body">
            {{ message }}
        </div>
    </div>
    {% endfor %}
</div>

<script>
        var toastElList = [].slice.call(document.querySelectorAll('.toast'))
        var toastList = toastElList.map(function (toastEl) {
            var toast = new bootstrap.Toast(toastEl)
            toast.show()
        })
</script>
{% endif %}

templates/tables/productsform.html
{% load i18n %}
{% load static %}

{% if productsform %}
<div class="row">
    <form method="post" id="products_form">
        {% csrf_token %}
        {{ productsform.management_form }}
        <table class="table table-hover">
            <thead class="table-secondary">
                <tr>
                    <th scope="col">{% trans 'Product' %}</th>
                    <th scope="col">{% trans 'Count' %}</th>
                    <th scope="col">{% trans 'Use pricelist' %}</th>
                    <th scope="col">{% trans 'Netto price' %}</th>
                    <th scope="col">{% trans 'VAT' %}</th>
                    <th scope="col">{% trans 'Brutto price' %}</th>
                    <th scope="col">{% trans 'Delete' %}</th>
                </tr>
            </thead>
            <tbody id="products_form-tbody">
                {% for form in productsform %}
                    {{ form.id }}
                    <tr id="row-{{ forloop.counter0 }}">
                        <td{% if form.errors.product %} class="table-danger"{% endif %}>{{ form.product }}</td>
                        <td{% if form.errors.count %} class="table-danger"{% endif %}>{{ form.count }}</td>
                        <td{% if form.errors.use_product_price %} class="table-danger"{% endif %}>
                            {{ form.use_product_price }}</td>
                        <td{% if form.errors.amount_netto_positiv %} class="table-danger"{% endif %}>
                            {{ form.amount_netto_positiv }}</td>
                        <td{% if form.errors.vat %} class="table-danger"{% endif %}>{{ form.vat }}</td>
                        <td{% if form.errors.amount_brutto_positiv %} class="table-danger"{% endif %}>
                            {{ form.amount_brutto_positiv }}</td>
                        <td>
                            {% if forloop.counter0 < productsform|length %}
                            <input type="hidden" name="products-{{ forloop.counter0 }}-DELETE"
                                   id="id_products-{{ forloop.counter0 }}-DELETE">
                            <button type="button" class="btn-close" onclick="deleteProduct({{ forloop.counter0 }});"
                                    id="id_products-{{ forloop.counter0 }}-delete-button"
                                    aria-label="{% trans 'close' %}">
                            </button>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                <tr id="products_form-empty_row" class="collapse">
                    <td>{{ productsform.empty_form.product }}</td>
                    <td>{{ productsform.empty_form.count }}</td>
                    <td>{{ productsform.empty_form.use_product_price }}</td>
                    <td>{{ productsform.empty_form.amount_netto_positiv }}</td>
                    <td>{{ productsform.empty_form.vat }}</td>
                    <td>{{ productsform.empty_form.amount_brutto_positiv }}</td>
                    <td></td>
                </tr>
            </tbody>
        </table>

        <div class="row">
            <div class="col">
                <button type="button" class="btn btn-outline-success mb-3" id="add_product_button"
                onclick="addProduct();">{% translate "Add product" %}
                </button>
            </div>
            <div class="col text-end">
                <button type="button" class="btn btn-outline-secondary mb-3 me-2" data-bs-dismiss="modal"
                        onClick="location.href=location.href">{% translate "Cancel" %}
                </button>
                <button type="submit" class="btn btn-success mb-3" name="editProducts" value="editProducts"
                        id="products_form_button" onclick="removeDisabled();">{% translate "Save" %}
                </button>
            </div>
        </div>

    </form>
</div>

<script src="{% static 'scripts/products_form.js' %}"></script>
{% endif %}

templates/tables/table_header.html
{% load i18n %}

<div class="row">

    {% include 'tables/table_header/breadcrumbs.html' %}

    <div class="col d-flex align-items-center justify-content-end">
        {% if form %}{% include "tables/table_header/form.html" %}{% endif %}
    </div>

    <div class="col d-flex align-items-center justify-content-end">

        {% include 'tables/table_header/project_select.html' %}

        {% include 'tables/table_header/date_filters.html' %}

        {% include 'tables/table_header/search_field.html' %}

        <input type="hidden" id="sort" name="sort">
        <input type="hidden" id="label" name="label">

    </div>

</div>

templates/tables/tables.html
{% extends "base/base.html" %}
{% load i18n %}

{% block title %}
    {{ breadcrumbs_titel }} - {% with breadcrumbs|last as last %}{{ last.text }}{% endwith %}
{% endblock %}

{% block content %}

    {% include 'tree/tree.html' %}

    {% include 'tables/table_header.html' %}

    {% include 'tables/labels.html' %}

    <div class="row" id="main-table">
        {% include 'tables/maintable.html' %}
    </div>

    {% include 'tables/productsform.html' %}

    {% include 'tables/tabs.html' %}

    {% include 'tables/messages.html' %}

{% endblock %}

templates/tables/tabs.html
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}
{% load render_table from django_tables2 %}

{% if tables %}
    <div class="tab">
        {% for tab in tables %}
            <button class="tablinks" onclick="openTab(event, '{{ tab.titel }}')"
                    {% if forloop.first %} id="defaultOpen"{% endif %}>
                {{ tab.titel }} ({{ tab.count }})
            </button>
        {% endfor %}
    </div>
    <div class="row">
        {% for tab in tables %}
            <div id="{{ tab.titel }}" class="tabcontent">
                <div class="row">
                    <div class="col">
                        {% if tab.table %}
                            <div class="row float-end">
                                <a href="{{ tab.link }}">
                                    <img class="m-1" src="{% static 'img/newtab.svg' %}"
                                         alt="{% translate 'In a new tab open...' %}" width="24" height="24"/>
                                </a>
                            </div>
                            {% render_table tab.table %}
                        {% endif %}

                        {% if tab.comments is not None %}
                            {% for comment in tab.comments %}
                                <div class="row mb-2">
                                    <div class="col">
                                        <span class="h6">{{ comment.object.author }}</span>&nbsp;
                                        <span class="text-muted">{{ comment.object.created }}</span><br>
                                        {{ comment.object.name }}<br>
                                        {% for file in comment.files %}
                                            <a href="{{ file.file.url }}" target="_blank">{{ file.name }}</a>&nbsp;
                                            &nbsp;
                                        {% endfor %}
                                    </div>
                                </div>
                            {% endfor %}

                            <button type="button" class="btn btn-outline-secondary mt-2" data-bs-toggle="modal"
                                    data-bs-target="#CommentForm">
                                {% translate "New comment" %}
                            </button>
                            <div class="modal fade" id="CommentForm" data-bs-backdrop="static" data-bs-keyboard="false"
                                 tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">

                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title"
                                                id="CommentFormLabel">{% translate "New comment" %}</h5>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                    aria-label="{% trans 'Close' %}"
                                                    onClick="location.href=location.href"></button>
                                        </div>
                                        <form method="POST" enctype="multipart/form-data" action="/comments">
                                            <div class="modal-body">
                                                {% csrf_token %}
                                                <input type="hidden" name="newCommentNextURL" id="newCommentNextURL"
                                                       value="{{ request.path }}">
                                                {{ tab.form|crispy }}
                                                <div class="mb-3">
                                                    <label for="id_file">{% translate "Files" %}</label>
                                                    <input name="file" class="form-control" type="file" id="id_file"
                                                           multiple>
                                                </div>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-outline-secondary"
                                                        data-bs-dismiss="modal"
                                                        onClick="location.href=location.href">{% translate "Close" %}
                                                </button>
                                                <button type="submit"
                                                        class="btn btn-success">{% translate "Send" %}</button>
                                            </div>

                                        </form>
                                    </div>
                                </div>
                            </div>

                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <script>document.getElementById("defaultOpen").click();</script>
{% endif %}

templates/tables/tree.html
{% if nodes %}
    <div class="row">
        <div class="col">
            <h2>Tree view:</h2>
            <ul class="list-group treeCSS ms-3">
                {% include 'tables/tree_item.html' %}
            </ul>
        </div>
    </div>
{% endif %}